name: build and deploy

on:
  # push:
  #   branches:
  #     - master
  repository_dispatch:
    types:
      - "study blog contents updated"

jobs:
  publish:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Gatsby Environment
        uses: actions/checkout@v2
        with:
          repository: "wand2016/study_gatsby"
          fetch-depth: 2
      - name: Checkout Contents
        uses: actions/checkout@v2
        with:
          repository: "wand2016/study"
          path: "content/blog"
          fetch-depth: 2
      - name: load commit hashes
        run: |
            echo "HASH_HEAD=$(git rev-parse HEAD)-$(git -C content/blog rev-parse HEAD)" | tee -a $GITHUB_ENV
            echo "HASH_PARENT=$(git rev-parse HEAD)-$(git -C content/blog rev-parse HEAD^)" | tee -a $GITHUB_ENV
      - name: cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            node-
      - name: install nodejs dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: npm ci

      - name: cache gatsby for HEAD
        uses: actions/cache@v2
        id: cache-gatsby-for_head
        with:
          path: |
            .cache
            public
          key: ${{ env.HASH_HEAD }}
      - name: "cache gatsby for HEAD^"
        if: steps.cache-gatsby-for_head.outputs.cache-hit != 'true'
        uses: actions/cache@v2
        with:
          path: |
            .cache
            public
          key: ${{ env.HASH_PARENT }}

      - name: build and put algolia indices
        run: npm run build
        env:
          TZ: Asia/Tokyo
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
          GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
          GATSBY_ALGOLIA_SEARCH_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY }}
          GATSBY_ALGOLIA_INDEX: ${{ secrets.GATSBY_ALGOLIA_INDEX }}
        timeout-minutes: 10

      - name: deploy to s3
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        timeout-minutes: 5

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
